const styles = {
    body: {
        fontFamily:
            '"Inter", "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
        backgroundColor: "#ffffff",
        color: "#2a3042",
        lineHeight: 1.6,
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        minHeight: "100vh",
        padding: "1.5rem",
    },
    resume: {
        width: "100%",
        maxWidth: "850px",
        background: "#ffffff",
        borderRadius: "16px",
        boxShadow:
            "0 20px 25px -5px rgba(0, 0, 0, 0.04), 0 10px 10px -5px rgba(0, 0, 0, 0.02)",
        overflow: "hidden",
        display: "grid",
        gridTemplateColumns: "1fr",
    },
    header: {
        background: "linear-gradient(135deg, #5c6bc0 0%, #42a5f5 100%)",
        padding: "2rem 3rem",
        color: "#ffffff",
        position: "relative",
        display: "flex",
        alignItems: "center",
        gap: "2rem",
    },
    headerContent: {
        flex: 1,
    },
    profileImageContainer: {
        position: "relative",
        zIndex: 2,
    },
    profileImage: {
        width: "120px",
        height: "120px",
        borderRadius: "16px",
        objectFit: "cover",
        border: "4px solid rgba(255, 255, 255, 0.3)",
        boxShadow:
            "0 10px 15px -3px rgba(0, 0, 0, 0.05), 0 4px 6px -2px rgba(0, 0, 0, 0.03)",
    },
    headerName: {
        fontSize: "1.875rem",
        fontWeight: 700,
        marginBottom: "0.25rem",
        letterSpacing: "-0.5px",
    },
    headerTitle: {
        fontSize: "1.125rem",
        fontWeight: 500,
        marginBottom: "1rem",
        opacity: 0.9,
    },
    contactBar: {
        display: "flex",
        flexWrap: "wrap",
        gap: "1.5rem",
    },
    contactItem: {
        display: "flex",
        alignItems: "center",
        fontSize: "0.875rem",
    },
    contactIcon: {
        marginRight: "0.5rem",
        opacity: 0.9,
        fontSize: "1.125rem",
    },
    mainContent: {
        padding: "3rem",
        display: "grid",
        gridTemplateColumns: "2fr 1fr",
        gap: "3rem",
    },
    contentSection: {
        marginBottom: "2rem",
    },
    sectionTitle: {
        fontSize: "1.25rem",
        color: "#5c6bc0",
        marginBottom: "1.5rem",
        fontWeight: 600,
        position: "relative",
        paddingBottom: "0.5rem",
        borderBottom: "3px solid transparent",
        backgroundImage: "linear-gradient(to right, #5c6bc0, #42a5f5)",
        backgroundSize: "40px 3px",
        backgroundRepeat: "no-repeat",
        backgroundPosition: "left bottom",
    },
    aboutMe: {
        fontSize: "1rem",
        color: "#505a74",
        lineHeight: 1.8,
        marginBottom: "2rem",
        padding: "1.5rem",
        backgroundColor: "#f9fbfe",
        borderRadius: "12px",
        border: "1px solid #e6eef7",
    },
    experienceCard: {
        backgroundColor: "#f9fbfe",
        borderRadius: "12px",
        padding: "1.5rem",
        marginBottom: "1.5rem",
        border: "1px solid #e6eef7",
        position: "relative",
    },
    experienceHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-start",
        marginBottom: "0.5rem",
    },
    jobTitle: {
        fontSize: "1.125rem",
        fontWeight: 600,
        color: "#2a3042",
    },
    jobDuration: {
        fontSize: "0.75rem",
        color: "#8896b8",
        backgroundColor: "#f1f8ff",
        padding: "0.25rem 0.5rem",
        borderRadius: "12px",
    },
    companyName: {
        fontSize: "1rem",
        color: "#505a74",
        marginBottom: "1rem",
        display: "flex",
        alignItems: "center",
    },
    companyIcon: {
        marginRight: "0.5rem",
        color: "#42a5f5",
    },
    jobDescription: {
        listStyle: "none",
        padding: 0,
    },
    jobDescriptionItem: {
        position: "relative",
        paddingLeft: "1.5rem",
        marginBottom: "0.5rem",
        color: "#505a74",
    },
    jobDescriptionBullet: {
        position: "absolute",
        left: 0,
        color: "#42a5f5",
    },
    skillsContainer: {
        display: "flex",
        flexWrap: "wrap",
        gap: "0.5rem",
        marginBottom: "1.5rem",
    },
    skillTag: {
        backgroundColor: "#f1f8ff",
        color: "#5c6bc0",
        fontSize: "0.875rem",
        padding: "0.4rem 0.8rem",
        borderRadius: "20px",
        display: "inline-block",
        fontWeight: 500,
    },
    languageItem: {
        marginBottom: "1rem",
    },
    languageInfo: {
        display: "flex",
        justifyContent: "space-between",
        marginBottom: "0.25rem",
    },
    languageName: {
        fontWeight: 500,
        color: "#505a74",
    },
    languageLevel: {
        fontSize: "0.75rem",
        color: "#8896b8",
    },
    languageBar: {
        height: "6px",
        backgroundColor: "#e9ecef",
        borderRadius: "3px",
        overflow: "hidden",
    },
    languageProgress: {
        height: "100%",
        background: "linear-gradient(to right, #5c6bc0, #42a5f5)",
        borderRadius: "3px",
    },
    hobbiesContainer: {
        display: "flex",
        flexWrap: "wrap",
        gap: "1rem",
    },
    hobbyItem: {
        display: "flex",
        alignItems: "center",
        backgroundColor: "#f1f8ff",
        padding: "0.5rem 1rem",
        borderRadius: "8px",
        fontSize: "0.875rem",
        color: "#505a74",
        fontWeight: 500,
    },
    hobbyIcon: {
        marginRight: "0.5rem",
        color: "#42a5f5",
    },
    pageContainer: {
        display: "flex",
        flexDirection: "column",
        maxWidth: "900px",
        margin: "0 auto",
        padding: "20px",
    },
    buttonContainer: {
        display: "flex",
        justifyContent: "center",
        gap: "20px",
        marginBottom: "20px",
    },
    button: {
        padding: "10px 20px",
        fontSize: "16px",
        fontWeight: "bold",
        backgroundColor: "#4a6cf7",
        color: "white",
        border: "none",
        borderRadius: "5px",
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        gap: "10px",
        transition: "background-color 0.3s ease",
        boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
    },
};
export default styles;